reservas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from reservas.views import reserva
from reservas.views import inicio



urlpatterns = [
    url(r'^sala/(?P<cd_recurso>\d+)/$', reserva.calendario , name='RESERVAS'),
    url(r'^sala/excluir/(?P<cd_reserva>\d+)/$', reserva.excluir, name='EXCLUIR'),
    url(r'^inicio/(?P<cd_recurso>\d+)/$', inicio.inicio, name='INICIO'),
    path('admin/', admin.site.urls),
]

reservas/forms/cadastroreserva.py
# -*- coding: UTF-8 -*-

from django import forms
from django.contrib.auth.models import User
import datetime
import datetime as dt
from reservas.models.recurso import Recurso
from reservas.models.reserva import Reserva
from reservas.models.usuario import Usuario

#form de cadastro inicial
#VALUES = [cd_reserva,ds_reserva,cd_recurso,cd_usuario,dt_inicio,dt_termino,erased,fl_recorrencia]

class CadastroReservaForm(forms.Form):

    def __init__(self, *args, **kwargs):

        self.request = kwargs.pop('request') #pegando o paramentro request que está lá na view e pasando pra dentro do form

        super(CadastroReservaForm, self).__init__(*args, **kwargs) #sei la porque +- tem uma metodo init na Class ReservaForm, então tenho que chamar no final pra ele se lembrar que tem que terminar de fazer o resto

############################################################################################################

    data = forms.CharField(widget=forms.DateInput(attrs={'id' :'datepicker', 'autocomplete': 'off'}))

############################################################################################################
    horaInicial = forms.CharField(widget=forms.TimeInput(attrs={'autocomplete': 'off'}))

############################################################################################################

    horaFinal = forms.CharField(widget=forms.TimeInput(attrs={'autocomplete': 'off'}))

############################################################################################################

    usuario = forms.CharField(widget=forms.TextInput())

############################################################################################################

    senha = forms.CharField(widget=forms.PasswordInput())

############################################################################################################
############################################################################################################

    def clean(self): #valida os dados que entraram no form

        cleaned_data = self.cleaned_data

        #validação usuário
        if not Usuario.objects.filter(ds_login=cleaned_data['usuario']).exists():
            raise forms.ValidationError('Usuario não existe')
        else:
            if not Usuario.objects.filter(ds_login=cleaned_data['usuario'],
                                          ds_senha=cleaned_data['senha']):
                raise forms.ValidationError('Senha incorreta')

        #recebe e formata dia atual
        hoje = datetime.datetime.today().date()
        hoje_30 = datetime.datetime.today() + dt.timedelta(days=30)
        hoje_30 = hoje_30.date()

        now_less = dt.datetime.today() - dt.timedelta(minutes=2)
        now_less = now_less.time()

        #get data
        data = cleaned_data['data']

        #removendo "/" da estring data
        newdata = data.replace("/", "")

        #tranformando a string data em dateObject
        objectdata = datetime.datetime.strptime(newdata, "%d%m%Y").date()

        #valida se data é maior ou igual a hoje
        if not objectdata >= hoje:
            raise forms.ValidationError('A data selecionada não pode ser inferior a data de hoje')

        if not objectdata <= hoje_30:
            raise forms.ValidationError('A data selecionada não pode ser superioir a 30 dias')

        #pega o cd_recurso que está no http request(na url)
        recurso = Recurso.objects.filter(cd_recurso=self.request.resolver_match.kwargs.get('cd_recurso'))

        #pega hora inicial e final (tryCatch verifica se o formato da entrada é válido)
        try:
            horaInicial = datetime.datetime.strptime(cleaned_data['horaInicial'], '%H:%M').time()
            horaFinal = datetime.datetime.strptime(cleaned_data['horaFinal'], '%H:%M').time()
        except:
            raise forms.ValidationError('Formato de hora inválido')


        #valida se hora final é maior ou igual que a hora inicial
        if horaFinal == horaInicial:
            raise forms.ValidationError('A hora final da reserva não pode ser igual a hora inicial')

        if not horaFinal > horaInicial:
            raise forms.ValidationError('A hora final da reserva não pode ser inferior a hora inicial')

        #if objectdata == hoje:
            #if not horaInicial > now_less:
             #   raise forms.ValidationError('A hora inicial da reserva não pode ser inferior a hora atual')

        #Criando datetime inicial e final - add/remove 1 segundo na hora inicial/final para poder realizar agendamentos sequentes
        timeInicial = dt.datetime.combine(objectdata, horaInicial) + dt.timedelta(seconds = 1)
        timeFinal = dt.datetime.combine(objectdata, horaFinal) - dt.timedelta(seconds = 1)


        # Checando a sala e as colisões
        # https://docs.djangoproject.com/en/dev/ref/models/querysets/#s-range
        start_conflict = Reserva.objects.filter(
            cd_recurso=self.request.resolver_match.kwargs.get('cd_recurso'),
            erased=0,
            dt_inicio__range=(timeInicial, timeFinal))

        end_conflict = Reserva.objects.filter(
            cd_recurso=self.request.resolver_match.kwargs.get('cd_recurso'),
            erased=0,
            dt_termino__range=(timeInicial,timeFinal))

        during_conflict = Reserva.objects.filter(
            cd_recurso=self.request.resolver_match.kwargs.get('cd_recurso'),
            erased=0,
            dt_inicio__lte=timeInicial, dt_termino__gte=timeFinal)

        if (start_conflict or end_conflict or during_conflict):
            booking = 'NOOOOOOOOOOOOOOOOOOOOOO!'
            raise forms.ValidationError('Agendamento não realizado. Horário não disponível.')

        else:
            booking ='Yes!!!!!!!'


        return cleaned_data

############################################################################################################
############################################################################################################

reservas/forms/inicio.py
# -*- coding: UTF-8 -*-

from django import forms
from django.contrib.auth.models import User
import datetime
import datetime as dt
from reservas.models.recurso import Recurso
from reservas.models.reserva import Reserva
from reservas.models.usuario import Usuario

class InicioForm(forms.Form):

############################################################################################################

    horaInicial = forms.CharField(widget=forms.TextInput())

############################################################################################################

    horaFinal = forms.CharField(widget=forms.TimeInput())

############################################################################################################
############################################################################################################

    def clean(self): #valida os dados que entraram no form

        cleaned_data = self.cleaned_data


        return cleaned_data

############################################################################################################
############################################################################################################

reservas/views/inicio.py
# -*- coding: UTF-8 -*-
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.shortcuts import render
import datetime as dt
from reservas.forms.inicio import InicioForm
from reservas.models.recurso import Recurso
from reservas.models.reserva import Reserva



def inicio(request, cd_recurso=0):

    if request.method == "POST":

        inicioForm = InicioForm(request.POST, request=request) #passando os dados da tela para dentro do form #request=request --> passando a http request pra poder pegar o id da sala pela url)

        if inicioForm.is_valid(): #verificando se os dados que entraram no campo são validos de acordo com o methodo clen (esta lá no form)

            pass

        else:

            return render(request, "index.html")


    else: #se não for post é get

        recurso = Recurso.objects.get(cd_recurso=cd_recurso)

        #verifica se há reserva agora
        now = dt.datetime.today()
        now_plus = dt.datetime.today() + dt.timedelta(seconds=10)

        during_conflict = Reserva.objects.filter(
            cd_recurso=cd_recurso,
            erased=0,
            dt_inicio__lte=now,
            dt_termino__gte=now_plus)

        #se há reserva agora, verifica horário de término da mesma
        if (during_conflict):
            during_conflict = Reserva.objects.get(
                cd_recurso=cd_recurso,
                erased=0,
                dt_inicio__lte=now,
                dt_termino__gte=now_plus)

            final = during_conflict.dt_termino
            final_plus = final + dt.timedelta(minutes=1)

            #verifica se tem reserva "colada" a reserva de agora
            try:
                next_reserva = Reserva.objects.get(
                    cd_recurso=cd_recurso,
                    erased=0,
                    dt_inicio__lte=final_plus,
                    dt_inicio__gte=final)

                final = next_reserva.dt_termino
                final_plus = final + dt.timedelta(minutes=1)

                #laço para próximas reservas "coladas"
                while(next_reserva):
                    next_reserva = Reserva.objects.get(
                        cd_recurso=cd_recurso,
                        erased=0,
                        dt_inicio__lte=final_plus,
                        dt_inicio__gte=final)

                    final = next_reserva.dt_termino
                    final_plus = final + dt.timedelta(minutes=1)

                final = final.time().__format__("%H:%M")
                final = str(final)

            except:
                #guarda tempo final para mandar pra tela
                final = final.time().__format__("%H:%M")
                final = str(final)

            messages.error(request, "Ocupada. Volte mais tarde. \n \n Próximo horário disponível: " + final +"h")

        else:

            reservas_ativas = Reserva.objects.filter(cd_recurso=cd_recurso,
                                                     erased=0,
                                                     dt_inicio__date__range=(dt.datetime.today(), dt.datetime.today() + dt.timedelta(days=30)))
            try:
                proxima_reserva = reservas_ativas.order_by('dt_inicio')[0]
                hrInicio = proxima_reserva.dt_inicio.time().__format__('%H:%M')
                dateInicio = proxima_reserva.dt_inicio.date()
                tomorrow = dt.datetime.today().date() + dt.timedelta(days=1)

            except:
                hrInicio = 0


            if hrInicio == 0:
                messages.success(request, "Livre. \n \n Recurso disponível durante os próximos 30 dias")
            else:
                if dateInicio > now.date():
                    if dateInicio == tomorrow:
                        messages.success(request, "Livre "
                                                  "\n \n O recurso está disponível durante o resto do dia. "
                                                  "\n \n Próxima reserva: Amanhã às " + hrInicio + "h")
                    else:
                        messages.success(request, "Livre "
                                                  "\n \n Recurso disponível durante o resto do dia. "
                                                  "\n \n Próxima reserva: Dia " + dateInicio.__format__('%d/%m/%y') + " às " + hrInicio + "h" )
                else:
                    messages.success(request, "Livre "
                                              "\n \n Recurso disponível até às " + hrInicio + "h")

        return render(request, "index.html", {'recurso': recurso, 'cd_recurso': cd_recurso})

############################################################################################################
############################################################################################################

reservas/views/inicio_bkup.py
# -*- coding: UTF-8 -*-
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.shortcuts import render
import datetime as dt
from reservas.forms.inicio import InicioForm
from reservas.models.recurso import Recurso
from reservas.models.reserva import Reserva



def inicio(request, cd_recurso=0):

    if request.method == "POST":

        inicioForm = InicioForm(request.POST, request=request) #passando os dados da tela para dentro do form #request=request --> passando a http request pra poder pegar o id da sala pela url)

        if inicioForm.is_valid(): #verificando se os dados que entraram no campo são validos de acordo com o methodo clen (esta lá no form)

            pass

        else:

            return render(request, "index.html")


    else: #se não for post é get

        recurso = Recurso.objects.get(cd_recurso=cd_recurso)

        #verifica se há reserva agora
        now = dt.datetime.today()
        now_plus = dt.datetime.today() + dt.timedelta(seconds=10)

        during_conflict = Reserva.objects.filter(
            cd_recurso=cd_recurso,
            erased=0,
            dt_inicio__lte=now,
            dt_termino__gte=now_plus)

        #se há reserva agora, verifica horário de término da mesma
        if (during_conflict):
            during_conflict = Reserva.objects.get(
                cd_recurso=cd_recurso,
                erased=0,
                dt_inicio__lte=now,
                dt_termino__gte=now_plus)

            final = during_conflict.dt_termino
            final_plus = final + dt.timedelta(minutes=1)

            #verifica se tem reserva "colada" a reserva de agora
            try:
                next_reserva = Reserva.objects.get(
                    cd_recurso=cd_recurso,
                    erased=0,
                    dt_inicio__lte=final_plus,
                    dt_inicio__gte=final)

                final = next_reserva.dt_termino
                final_plus = final + dt.timedelta(minutes=1)

                #laço para próximas reservas "coladas"
                while(next_reserva):
                    next_reserva = Reserva.objects.get(
                        cd_recurso=cd_recurso,
                        erased=0,
                        dt_inicio__lte=final_plus,
                        dt_inicio__gte=final)

                    final = next_reserva.dt_termino
                    final_plus = final + dt.timedelta(minutes=1)

                final = final.time().__format__("%H:%M")
                final = str(final)

            except:
                #guarda tempo final para mandar pra tela
                final = final.time().__format__("%H:%M")
                final = str(final)

            messages.error(request, "Ocupada. Volte mais tarde. \n \n Próximo horário disponível: " + final +"h")

        else:
            # verifica próximo horário disponível
            now = dt.datetime.today()
            plusMin = 10
            # define último horário a buscar (se não, entra em looop - 20h)
            endTime = 20
            cont_time = now.time().__format__('%H')
            cont_time = int(cont_time)

            while cont_time < endTime:
                increment_now = dt.datetime.today() + dt.timedelta(minutes=plusMin)
                cont_time = increment_now.time().__format__('%H')
                cont_time = int(cont_time)
                start_conflict = Reserva.objects.filter(
                    cd_recurso=cd_recurso,
                    erased=0,
                    dt_inicio__range=(now, increment_now))

                if not start_conflict:
                    plusMin = plusMin + 10
                else:
                    cont_time = endTime

            try:
                start_conflict = Reserva.objects.get(
                    cd_recurso=cd_recurso,
                    erased=0,
                    dt_inicio__range=(now, increment_now))

                hrInicio = start_conflict.dt_inicio
                hrInicio = hrInicio.time().__format__('%H:%M')
                hrInicio = str(hrInicio)

            except:
                hrInicio = 0

            if hrInicio == 0:
                messages.success(request, "Livre. \n \n Recurso disponível durante o resto do dia")
            else:
                messages.success(request, "Livre. \n \n Recurso disponível até as " + hrInicio + "h")

        return render(request, "index.html", {'recurso': recurso, 'cd_recurso': cd_recurso})

############################################################################################################
############################################################################################################

reservas/templates/old/calendar_bkup.html
<!DOCTYPE html>
<html lang="pt-br" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agendamento de salas de reunião</title>
    {% load static %}
    {% load tags %}
    <link href="{% static 'assets/css/bootstrap.min_old.css' %}" type="text/css" rel="stylesheet" />
    <link href="{% static 'assets/css/fullcalendar.min.css' %}" type="text/css" rel="stylesheet" />
    <link href="{% static 'assets/css/style.css' %}" type="text/css" rel="stylesheet">
    <!-- Icons -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    <!-- Autocomplete input -->
    <link rel="stylesheet" href="{% static 'assets/js/autocomplete/jquery-ui.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/js/autocomplete/autocomplete.css' %}" />
    <!-- TimePicker -->
    <link rel="stylesheet" href="{% static 'assets/js/timepicker/timepicker_style.css' %}" />

    <script src="{% static 'assets/js/jquery.js' %}"></script>
    <!-- Input Mask -->
    <script src="{% static 'assets/js/jquery.inputmask.js' %}"></script>
    <!-- Autocomplete Input -->
    <script src="{% static 'assets/js/autocomplete/jquery-ui.js' %}"></script>
    <!-- Calendario -->
    <script src="{% static 'assets/js/moment.min.js' %}"></script>
    <script src="{% static 'assets/js/fullcalendar.min.js' %}"></script>
    <script src="{% static 'assets/js/locale-all.js' %}"></script>
    <!-- Modal -->
    <script src="{% static 'assets/js/bootstrap.min_old.js' %}"></script>
    <script src="{% static 'assets/js/script.js' %}"></script>
    <!-- TimePicker -->
    <script src="{% static 'assets/js/timepicker/timepicker.js' %}"></script>
</head>
<body>
    <!-- BEGIN: Tela calendário -->
    <div class="wrap-content">

        <div class="content">
            {% if messages %}
                {% for message in messages %}
                    <div{% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissable" role="alert" {% endif %}>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        {{ message }}</div>
                {% endfor %}
            {% endif %}
            <div class="nome-recurso">{{ recurso }}</div>
            <div id="calendar"></div>
        </div>
        <a class="plus">
            <i class="fa fa-plus"></i>
        </a>
        <a class="home" href="../../inicio/{{ cd_recurso }}/">
            <i class="fa fa-home"></i>
        </a>
    </div>
    <!-- // END: Tela calendário -->

    <!-- BEGIN: Modal ver agendamento -->
    <div id="fullCalModal" class="modal fade">
        <form class="form-horizontal" role="form" method="post" id="form-exclude"> {% csrf_token %}
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <strong>Detalhes da reserva</strong>
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span></button>
                    </div>
                    <div class="modal-body form-excluir">
                        <table>
                            <tr>
                                <td>Código: </td>
                                <td>{{ excluirReservaForm.reserva|addcss:'input-excluir' }}</td>
                            </tr>
                            <tr>
                                <td>Responsável:</td>
                                <td><input type="text" id="id_responsavel" class="input-excluir" disabled></td>
                            </tr>
                            <tr>
                                <td>Recurso:</td>
                                <td><input type="text" id="id_recurso" class="input-excluir" disabled></td>
                            </tr>
                            <tr>
                                <td>Data:</td>
                                <td><input type="text" id="id_data" class="input-excluir" disabled></td>
                            </tr>
                            <tr>
                                <td>Hora Inicial</td>
                                <td><input type="text" id="id_horaInicial" class="input-excluir" disabled></td>
                            </tr>
                            <tr>
                                <td>Hora Final</td>
                                <td><input type="text" id="id_horaFinal" class="input-excluir" disabled></td>
                            </tr>
                        </table>
                        <div class="validation" style="display: none">
                            <p> Para realizar a exclusão entre com seu usuario e senha TargetSka:</p>
                            <table class="table-excluir">
                                <tr>
                                    <td>Usuario</td>
                                    <td>{{ excluirReservaForm.usuario|addcss:'form-control addresspicker'}}</td>
                                </tr>
                                <tr>
                                    <td>Senha</td>
                                    <td>{{ excluirReservaForm.senha|addcss:'form-control'}}</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                        <div class="btn btn-primary" id="show-validation">Excluir</div>
                        <div id="showBtn" style="display: none; float: right; margin-left: 5px">
                            <button type="submit" class="btn btn-primary">Confirmar Exclusão</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <!-- // END: Modal ver agendamento -->
    <!-- BEGIN: Modal realizar agendamento - Data e hora atual -->
    <div id="reserva-currentDate" class="modal fade">
        <form style="height: 100%" class="form-horizontal" role="form" method="post"> {% csrf_token %}
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <strong>Reservar Sala 1</strong>
                        <button type="button" class="close" data-dismiss="modal">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body form-reserva">
                        <table>
                            <tr>
                                <td>Data:</td>
                                <td>{{ cadastroReservaForm.data|addcss:'form-control date' }}</td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>Hora Inicial:</td>
                                <td><div id="sample1">{{ cadastroReservaForm.horaInicial|addcss:'form-control' }}</div></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>Hora Final:</td>
                                <td><div id="sample1">{{ cadastroReservaForm.horaFinal|addcss:'form-control' }}</div></td>
                                <td>
                                    <button type="button" class="add-minutos" onclick="incre15()">+15'</button>
                                    <button type="button" class="add-minutos" onclick="incre30()">+30'</button>
                                    <button type="button" class="add-minutos" onclick="incre60()">+1h</button>
                                </td>
                            </tr>
                            <tr>
                                <td>Usuario</td>
                                <td>{{ cadastroReservaForm.usuario|addcss:'form-control addresspicker' }}</td>
                            </tr>
                            <tr>
                                <td>Senha</td>
                                <td>{{ cadastroReservaForm.senha|addcss:'form-control' }}</td>
                            </tr>
                        </table>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-primary" >Reservar</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <!-- // END: Modal realizar agendamento - Data e hora atual -->

    <script>
    // ::: Script Input Mask :::
    $(function(){
        $('input[class$="date"]').inputmask(
        "dd/mm/yyyy", {
        placeholder: "DD/MM/AAAA",
        dateFormat: 'dd/mm/yyyy',},
      );
    });
    // ::: Script Autocomplete :::
    $(function() {
        var availableTags =
            [
               {% for item in usuarios %}
                   "{{ item.ds_login|cut:" "  }}",
               {% endfor %}
            ];
            $( ".addresspicker" ).autocomplete({
              source: availableTags
            });
        });
    // ::: Script Calendar :::
    $(document).ready(function() {
        $('#calendar').fullCalendar({
            height: 750,
            hiddenDays: [0],
            selectable: true,
            editable: true,
            defaultView: 'agendaDay', // Seta qual caledario aparece no início (Mês, semana, dia )
            header: {
                left: 'prev,next',
                center: 'title',
                right: 'agendaWeek,agendaDay'
            },
            allDaySlot: false, // Remove all day events do topo da tabela
            defaultDate: moment(), // Pega current Data
            navLinks: true, //
            locale: 'pt-br', //idioma
            eventLimit: true, //
            eventStartEditable: false, // Não permiti editar eventos por arrastamento
            eventDurationEditable: false, // Não permiti editar eventos por meio de redimensionamento
            minTime: "08:00:00", // Definindo tempo inicial e final do calendario
            maxTime: "19:00:00",
            validRange: { // Range de dias a mostrar - setado para 30 dias(mudar no django também)
                start: moment().subtract(1, 'days'),
                end: moment().add(30, 'days')
            },
            viewRender: function(view) {
                // Disabilitando botões dia anterior
                if(moment().isAfter(view.intervalStart, 'day')) {
                    $('.fc-prev-button').addClass('fc-state-disabled');
                } else {
                    $('.fc-prev-button').removeClass('fc-state-disabled');
                }
                $('body').remove('.fc-listWeek-button');
            },
            eventClick: function(event, jsEvent, view) { // Abre modal com as informações do agendamento
                $('#modalTitle').html(event.title);
                $('#modalBody').html(
                    document.getElementById("id_reserva").value = event.code,
                    document.getElementById("id_responsavel").value = event.title,
                    document.getElementById("id_recurso").value = event.resource,
                    document.getElementById("id_data").value = event.start.format("DD/MM/YYYY"),
                    document.getElementById("id_horaInicial").value = event.start.format("HH:mm"),
                    document.getElementById("id_horaFinal").value = event.end.format("HH:mm"),
                    document.getElementById('form-exclude').action = '../excluir/' + event.code + '/',

                    // mostrar campos de usuario e senha para validar
                    $('#show-validation').click(function() {
                        $('.validation').slideDown(400);
                        document.getElementById("show-validation").style.display="none";
                        document.getElementById("showBtn").style.display="block";
                    }),
                    $('.btn-default, .close').click(function() { // oculta campos usuario e senha qnd modal é fechado
                        $('.validation').slideUp(400);
                        document.getElementById("show-validation").style.display="inline";
                        document.getElementById("showBtn").style.display="none";
                    }),
                );
                $('#eventUrl').attr('href', event.url);
                $('#fullCalModal').modal();
                return false;
            },
            events: [
                {% for item in reservas %}
                {
                    code: '{{ item.cd_reserva }}',
                    title: '{{ item.cd_usuario }}',
                    resource: '{{ item.cd_recurso }}',
                    start: '{{ item.dt_inicio }}',
                    end: '{{ item.dt_termino }}',
                    description: "{{ item.ds_reserva }}",
                },
                {% endfor %}]
            });
          });
    // ::: Script timePicker :::
    $(document).ready(function(){
        // find the input fields and apply the time select to them.
        $('#sample1 input').ptTimeSelect({
            timeFormat: "HH:mm",
        });
    });
    </script>
</body>
</html>